### ISSUE TITLE
Shift + direction with numpad not running

### ISSUE THREAD

**Issue by NickMcConnell** [NickMcConnell/FirstAgeAngband#153]
Reported by Sasquatch from angband.live

**Comment by NickMcConnell** [comment]
SDL2 port only

**Comment by backwardsEric** [comment]
Is this a regression due to https://github.com/angband/angband/commit/7fb1b056eb40fc9cd94cec6ab3b3e5d0bdb2e387#diff-8698e4333ff4cc77630e13f4f190894f396bdab8d056717aed782e822e0cdaab ?  Testing in a VM on a Mac (with the additional complication of an external keyboard to get a numeric keypad), I see the same behavior with Vanilla Angband - shit+keypad direction does not run.  Turning on the send keypad modifier option introduced in that commit restores the running behavior.  If it is that commit, could back it out  or change the default so the numeric keypad modifier is sent unless its explicitly turned off for compatibility with other keyboard layouts.
