### ISSUE TITLE
Misc. Monster Adjustments

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/FirstAgeAngband#170]
Winged Dragons of Annihilation breathe poison and nether but don't resist either; this feels weird, and I thought breathers generally resisted their breath elements besides.

Bronze Golems breathe fire 1 in 50; this seems ludicrously rare and is out of place for monster casting/breathing rarities as far as I've seen.

**Comment by NickMcConnell** [comment]
Yes, I was assuming this happened automatically (as in old FA), but it doesn't.  There are a few other monsters with similar issues.
Bronze golems are like that because they cast very rarely, so when spell spells and innate spells (breaths, boulders etc) got separated, their frequency of breathing became a fifth of not much.  So deliberate, if a bit weird.
