### ISSUE TITLE
RFE: Buff Length Alignment

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/FirstAgeAngband#184]
Requesting that spells like the mage's Resistance (where it's actually multiple buffs activated by one spell) aligns the durations of the activated buffs where the potential durations align; frankly, I think it's just annoying to cast e.g. Resistance and to have rAcid, rElec, rFire, and rCold all wear off one at a time instead of all at once.

To wit: when casting Resistance (or any other spell with a similar situation), instead of rolling the duration of each temporary resistance separately, roll the duration beforehand and pass it on to all the resistance timers.

**Comment by NickMcConnell** [comment]
This one's a bit annoying to implement - I'll have to think about it.

**Comment by backwardsEric** [comment]
One possibility would be to define two effects, SET_SHARED_DICE and CLEAR_SHARED_DICE (for lack of better names).  The first would set a flag in effect_do() so that later effects in the chain would use the value rolled for the dice expression set for the SET_SHARED_DICE effect rather than their own dice expression.  The second would clear that flag so that effects after it (until the next use of SET_SHARED_DICE) would each use their own random roll.

**Comment by NickMcConnell** [comment]
I was thinking of something along the same lines.  I had thought a SET_VALUE  - but hadn't thought of clearing afterwards.

**Comment by NickMcConnell** [comment]
I think I'll start simple and just do a SET and CLEAR with as little other change as possible for now.  I do think that having separate routines for traversing the effect chain is something we want to do.   I'm not sure whether there are other bits of state we want to carry through the chain, but if we go on to allow that it will probably get used somewhere (possibly even for the things suggested [here](http://angband.oook.cz/forum/showpost.php?p=153826&postcount=118) and in the following posts, although I haven't thought that through).

**Comment by NickMcConnell** [comment]
Basic version done in f7c8b56c7.
