### ISSUE TITLE
Bug: 'Drain Experience' Runes

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/FirstAgeAngband#192]
In the rune knowledge menu, experience drain is listed twice: once under Curses, and again under Other.

When you ID it through, say, Identify Rune, only one of them is actually IDed; for the other, you actually have to wear something with the rune (and for the rune to trigger?) for it to ID.

This is inconsistent, and I don't understand why drain experience is listed twice to begin with (IIRC there are some other curses that act the same way, but drain experience is the only one I can verify right now).

**Comment by ThatGitMITZE** [comment]
This also applies to the 'Impaired Mana Recovery' rune.

**Comment by NickMcConnell** [comment]
DRAIN_EXP and IMPAIR_MANA are object flags, so an object could have them directly (and in V a bunch do have DRAIN_EXP, like the One Ring).  They are also used in curses, so the experience drain curse just gives DRAIN_EXP - but can be removed from the object.

I think the ID situation needs clarification - probably you should just learn both runes if you have the curse.  This goes for V too.

**Comment by NickMcConnell** [comment]
Actually, no, I think current behaviour is probably correct.  Take DRAIN_EXP as an example.  There are two separate runes - the experience drain curse and the DRAIN_EXP flag.  If you wear the item and discover the property that way, you learn both runes.  If you use Identify Rune, you learn at random a rune the object has, so of those two that can only be the curse rune, because the object actually doesn't have the DRAIN_EXP flag.  The only way to learn the DRAIN_EXP flag is to wear the item, because DRAIN_EXP is a property of the curse, not the item, and you can't cast Identify Rune on the curse.

So correct player behaviour here is cast Identify Rune, find you have the experience drain curse, say "I wonder what that does", put on the item, learn the DRAIN_EXP rune.

**Comment by NickMcConnell** [comment]
Understanding that was a good exercise for me to go through, though 😃
