### ISSUE TITLE
Monster Knowledge

### ISSUE THREAD

**Issue by NickMcConnell** [NickMcConnell/FirstAgeAngband#51]
"There appears to be some sort of (possibly only) display bug with the monster knowledge display under ~; there are things I've definitely killed with my current character that the game tells me I've killed none of. Perhaps related to the rune knowledge bug somehow?" - MITZE

**Comment by backwardsEric** [comment]
Is the location of the user's files contributing to this and #75 , at least on OS X?  For the OS X front end, the same directory, ~/Documents/Angband, is used as in Angband.  In my case, I've been going back and forth between First Age and Angband.  The history of my character in First Age has Pongo, Thief of the Mountains, and Balcmeg among the uniques killed, but lore.txt does not list them, but that lore.txt has been read and written by Angband multiple times since the character in First Age was created.

**Comment by NickMcConnell** [comment]
Guessing this is OK now
